### ISSUE TITLE
Pip install fails with use-pep517 option

### ISSUE THREAD

**Issue by fx-kirin** [PyO3/setuptools-rust#231]
```
pip install --use-pep517 .
```

The command above doesn't work with `setuptools-rust`. Even example code in this repo fails saying 'no module named setuptools-rust`. I think this happens because pip uses the tmp directory to build the package with the option.

## Environment

- Ubuntu 20.04
- Python 3.10
- Pip 22.1.1
- Setuptoosl-rust 1.2.0

## Error message

```
Processing /home/username/github/setuptools-rust/examples/html-py-ever
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "/home/username/.pyenv/versions/3.10.4/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/username/.pyenv/versions/3.10.4/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/username/.pyenv/versions/3.10.4/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-abfeo985/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/tmp/pip-build-env-abfeo985/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-abfeo985/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 281, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-abfeo985/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 6, in <module>
          from setuptools_rust import RustExtension
      ModuleNotFoundError: No module named 'setuptools_rust'
      [end of output]
```

Poetry forces users to use this option on installing packages to virtual environment.

**Comment by messense** [comment]
The examples are missing `pyproject.toml`, I'm adding them in #232.

See https://setuptools-rust.readthedocs.io/en/latest/#pyproject-toml

**Comment by fx-kirin** [comment]
Thanks!
