### ISSUE TITLE
release version is not working on osx

### ISSUE THREAD

**Issue by apatrushev** [PyO3/setuptools-rust#6]
Release version broken:
```sh
rust|user@host ~ $ python --version
Python 3.5.3

rust|user@host ~ $ git clone https://github.com/PyO3/setuptools-rust.git
Cloning into 'setuptools-rust'...
[...skipped...]

rust|user@host ~ $ cd setuptools-rust/
rust|user@host ~/setuptools-rust $ pip install .
Processing /Users/user/setuptools-rust
[..skipped..]

rust|user@host ~/setuptools-rust $ cd example/
rust|user@host ~/setuptools-rust/example $ pip install .
Processing /Users/user/setuptools-rust/example
Installing collected packages: hello-rust
  Running setup.py install for hello-rust ... done
Successfully installed hello-rust-1.0

rust|user@host ~/setuptools-rust/example $ pip freeze
appdirs==1.4.3
hello-rust==1.0
packaging==16.8
pyparsing==2.2.0
semantic-version==2.6.0
setuptools-rust==0.5.1
six==1.10.0

rust|user@host ~/setuptools-rust/example $ python -c 'import hello_rust; hello_rust.hello()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/user/setuptools-rust/example/hello_rust/__init__.py", line 1, in <module>
    from . import _helloworld
ImportError: cannot import name '_helloworld'
```

Debug version is working fine:
```sh
[...same steps from scratch as above...]

rust|user@host ~/setuptools-rust $ cd example/
rust|user@host ~/setuptools-rust/example $ pip install -e .
Obtaining file:///Users/user/setuptools-rust/example
Installing collected packages: hello-rust
  Running setup.py develop for hello-rust
Successfully installed hello-rust

rust|user@host ~/setuptools-rust/example $ pip freeze
appdirs==1.4.3
-e git+https://github.com/PyO3/setuptools-rust.git@4272c1c8d2dcd383e935bfe87913098a9fe4cc88#egg=hello_rust&subdirectory=example
packaging==16.8
pyparsing==2.2.0
semantic-version==2.6.0
setuptools-rust==0.5.1
six==1.10.0

rust|user@host ~/setuptools-rust/example $ python -c 'import hello_rust; hello_rust.hello()'
Rust says: Hello Python!
Rust got 42
```

**Comment by fafhrd91** [comment]
thanks for reporting, I will into this problem.

**Comment by fafhrd91** [comment]
@apatrushev you run `python -c 'import hello_rust; hello_rust.hello()'` from directory with hello_rust source. so python use it instead of version from site-package. just change directory and try again.

**Comment by apatrushev** [comment]
Oops... Thank you @fafhrd91!
