### ISSUE TITLE
Conflict when running bdist_wheel

### ISSUE THREAD

**Issue by casellimarco** [PyO3/setuptools-rust#75]
With the new release 0.11.0 there is an issue when trying to create a package by running:
`python setup.py bdist_wheel`
we got this error: 
```Traceback (most recent call last):
  File "setup.py", line 33, in <module>
    'hdbscan', 'oni-analysis~=3.1'],
  File "/home/********/repo/venv/lib/python3.6/site-packages/setuptools/__init__.py", line 140, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/********/repo/venv/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 259, in run
    self.run_command('install')
  File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.6/distutils/command/install.py", line 557, in run
    self.run_command(cmd_name)
  File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/********/repo/venv/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 12, in run
    outfiles = self.install()
  File "/usr/local/lib/python3.6/distutils/command/install_lib.py", line 111, in install
    outfiles = self.copy_tree(self.build_dir, self.install_dir)
  File "/home/********/repo/venv/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 91, in copy_tree
    exclude = self.get_exclusions()
  File "/home/********/repo/venv/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 24, in get_exclusions
    for ns_pkg in self._get_SVEM_NSPs()
  File "/home/********/repo/venv/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 61, in _get_SVEM_NSPs
    svem = install_cmd.single_version_externally_managed
  File "/usr/local/lib/python3.6/distutils/cmd.py", line 103, in __getattr__
    raise AttributeError(attr)
AttributeError: single_version_externally_managed
```

Rolling back to 0.10.6 solved the issue.

**Comment by davidhewitt** [comment]
Thanks for reporting, are you able to provide an example repository which demonstrates this issue?

**Comment by casellimarco** [comment]
It happened locally and on circleCi on several private repositories, sorry I cannot share them.

**Comment by casellimarco** [comment]
We tested it against several versions of setuptools

**Comment by davidhewitt** [comment]
Understood. Are you provide a minimal reproduction which does not expose your private content?

**Comment by davidhewitt** [comment]
A quick follow up - I tested locally with the `setuptools-rust` examples and cannot reproduce this issue. Without a reproduction I'm afraid we will not be able to fix.

**Comment by casellimarco** [comment]
It took me a while to reproduce it, it was really unclear the source of the issue. 
It seems it is due to having nested namespaces. 
Here you can have a play, there is bash script that will reproduce the error
https://github.com/casellimarco/dummy_setuptool_rust

**Comment by davidhewitt** [comment]
🚀 many thanks - I'll see if I can debug tomorrow!

**Comment by davidhewitt** [comment]
@casellimarco I've release `setuptools-rust==0.11.2b0` - can you please retry your CI with this version and confirm if it works? If so, then I will release `0.11.2`.

**Comment by casellimarco** [comment]
Amazing, tested and it works fine! Many thanks, glad to see such a small diff to fix it  =)
